version: '2'
services:
    nginx:
        build:
          context: .
          dockerfile: Dockerfile-local
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ./testfiles:/mnt/mixes:ro
            - ./templates:/app/templates
            - ./style:/app/style
            - ./img:/app/img
            - ./hotmixes:/app/hotmixes
            - ./goaccess:/app/goaccess:ro
        tmpfs:
            - /tmp
