version: '2'
services:
    nginx:
        build:
          context: .
          dockerfile: Dockerfile-local
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ~/Music:/mnt/mixes:ro
