FROM openresty/openresty:1.19.3.1-1-alpine-fat

RUN apk add openssl-dev git
RUN apk add --no-cache curl perl
RUN luarocks install --server=http://luarocks.org/dev lua-resty-template
RUN opm get spacewander/luafilesystem

RUN apk --no-cache add findutils
RUN apk --no-cache add coreutils

WORKDIR /app

COPY nginx-local.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
